site_name: Study Notes
site_url: https://17kaushalsingh.github.io/study-notes/

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: README.md

  - DSA & CP:
      - Overview: dsa-and-cp/index.md

  - Systems & Backend:
      - Backend From First Principles: systems-and-backend/backend-from-first-principles/README.md

      - Low Level Design: systems-and-backend/low-level-design/README.md

  - Databases:
      - Database System Concepts: databases/README.md

  - Languages:
      - Java: languages/java/LEC1_Core_Java.md
      - C++: languages/learn-cpp/README.md